-- Create books table
CREATE TABLE IF NOT EXISTS books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(255) NOT NULL,
    department VARCHAR(100) DEFAULT 'Software Engineering',
    description TEXT,
    cover_color VARCHAR(50) DEFAULT 'linear-gradient(135deg, #1e3c72, #2a5298)',
    shelf_location VARCHAR(50),
    total_copies INT DEFAULT 5,
    available_copies INT DEFAULT 5,
    topics TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Seed 50 Software Engineering books
INSERT INTO books (title, author, description, shelf_location, topics, cover_color) VALUES 
('Clean Code', 'Robert C. Martin', 'A Handbook of Agile Software Craftsmanship.', 'Shelf 1A', 'Agile, Clean Code, Best Practices', 'linear-gradient(135deg, #2c3e50, #000000)'),
('Design Patterns', 'Erich Gamma, Richard Helm, Ralph Johnson, John Vlissides', 'Elements of Reusable Object-Oriented Software.', 'Shelf 2B', 'OOP, Design Patterns, Architecture', 'linear-gradient(135deg, #1e3c72, #2a5298)'),
('The Pragmatic Programmer', 'Andrew Hunt, David Thomas', 'From Journeyman to Master.', 'Shelf 1A', 'Programming, Professionalism, Career', 'linear-gradient(135deg, #2c3e50, #4ca1af)'),
('Introduction to Algorithms', 'Thomas H. Cormen', 'The standard textbook for algorithm design.', 'Shelf 3C', 'Algorithms, Data Structures, Theory', 'linear-gradient(135deg, #2ecc71, #27ae60)'),
('The Mythical Man-Month', 'Frederick P. Brooks Jr.', 'Essays on Software Engineering.', 'Shelf 4D', 'Management, Project Management, History', 'linear-gradient(135deg, #e67e22, #d35400)'),
('Refactoring', 'Martin Fowler', 'Improving the Design of Existing Code.', 'Shelf 2B', 'Refactoring, Code Quality, Maintenance', 'linear-gradient(135deg, #8e44ad, #9b59b6)'),
('Code Complete', 'Steve McConnell', 'A Practical Handbook of Software Construction.', 'Shelf 1A', 'Construction, Best Practices, Quality', 'linear-gradient(135deg, #34495e, #2c3e50)'),
('Head First Design Patterns', 'Eric Freeman', 'A Brain-Friendly Guide.', 'Shelf 2B', 'Design Patterns, Visual Learning, CS', 'linear-gradient(135deg, #f1c40f, #e67e22)'),
('Clean Architecture', 'Robert C. Martin', 'A Craftsman Guide to Software Structure.', 'Shelf 2B', 'Architecture, Clean Code, Systems', 'linear-gradient(135deg, #3498db, #2980b9)'),
('Domain-Driven Design', 'Eric Evans', 'Tackling Complexity in the Heart of Software.', 'Shelf 2B', 'DDD, Architecture, Modeling', 'linear-gradient(135deg, #16a085, #1abc9c)'),
('Pattern Recognition and Machine Learning', 'Christopher Bishop', 'Introduction to PRML.', 'Shelf 5E', 'ML, AI, Mathematics', 'linear-gradient(135deg, #444, #111)'),
('Artificial Intelligence: A Modern Approach', 'Stuart Russell', 'Comprehensive AI guide.', 'Shelf 5E', 'AI, Robotics, Logic', 'linear-gradient(135deg, #16a085, #1abc9c)'),
('Computer Networking', 'Behrouz A. Forouzan', 'Fundamentals of networking.', 'Shelf 6F', 'Networks, Protocols, TCP/IP', 'linear-gradient(135deg, #f39c12, #e67e22)'),
('Database System Concepts', 'Abraham Silberschatz', 'Foundations of DBMS.', 'Shelf 3C', 'Databases, SQL, NoSQL', 'linear-gradient(135deg, #2980b9, #3498db)'),
('Modern Operating Systems', 'Andrew S. Tanenbaum', 'Concepts of OS design.', 'Shelf 4D', 'OS, Kernel, Concurrency', 'linear-gradient(135deg, #c0392b, #e74c3c)'),
('Compilers: Principles, Tech, and Tools', 'Alfred Aho', 'The "Dragon Book".', 'Shelf 3C', 'Compilers, Languages, Theory', 'linear-gradient(135deg, #8e44ad, #2c3e50)'),
('Software Engineering', 'Ian Sommerville', 'Comprehensive SE overview.', 'Shelf 1A', 'SE, Lifecycle, Agile', 'linear-gradient(135deg, #27ae60, #2ecc71)'),
('Unit Testing Principles, Practices, and Patterns', 'Vladimir Khorikov', 'Guide to effective unit testing.', 'Shelf 2B', 'Testing, Unit Testing, Quality', 'linear-gradient(135deg, #2980b9, #2c3e50)'),
('Software Architecture in Practice', 'Len Bass', 'Applying architecture concepts.', 'Shelf 2B', 'Architecture, Patterns, Quality', 'linear-gradient(135deg, #7f8c8d, #2c3e50)'),
('Effective Java', 'Joshua Bloch', 'Best practices for Java.', 'Shelf 1A', 'Java, Programming, Patterns', 'linear-gradient(135deg, #e67e22, #f39c12)'),
('Eloquent JavaScript', 'Marijn Haverbeke', 'A Modern Guide to Programming.', 'Shelf 1A', 'JavaScript, Web, Programming', 'linear-gradient(135deg, #f1c40f, #333)'),
('Cracking the Coding Interview', 'Gayle Laakmann McDowell', '189 Programming Questions.', 'Shelf 1A', 'Interviews, Algorithms, Career', 'linear-gradient(135deg, #2ecc71, #34495e)'),
('Structure and Interpretation of Computer Programs', 'Harold Abelson', 'SICP - Foundations of CS.', 'Shelf 3C', 'Scheme, Functional Programming, Theory', 'linear-gradient(135deg, #c0392b, #333)'),
('Soft Skills: The Software Developer\'s Life Manual', 'John Sonmez', 'Beyond coding.', 'Shelf 1A', 'Career, Soft Skills, Productivity', 'linear-gradient(135deg, #3498db, #f39c12)'),
('Working Effectively with Legacy Code', 'Michael Feathers', 'Managing existing codebases.', 'Shelf 2B', 'Legacy Code, Testing, Refactoring', 'linear-gradient(135deg, #7f8c8d, #333)'),
('Test Driven Development: By Example', 'Kent Beck', 'TDD methodology.', 'Shelf 2B', 'TDD, Testing, Agile', 'linear-gradient(135deg, #1abc9c, #333)'),
('Extreme Programming Explained', 'Kent Beck', 'XP principles.', 'Shelf 1A', 'XP, Agile, Management', 'linear-gradient(135deg, #e74c3c, #333)'),
('Agile Estimating and Planning', 'Mike Cohn', 'Agile management.', 'Shelf 1A', 'Agile, Planning, Scrum', 'linear-gradient(135deg, #2980b9, #333)'),
('The Clean Coder', 'Robert C. Martin', 'Conduct of Professional Programmers.', 'Shelf 1A', 'Professionalism, Ethics, Career', 'linear-gradient(135deg, #2c3e50, #000)'),
('Head First Agile', 'Andrew Stellman', 'Agile learning.', 'Shelf 1A', 'Agile, Scrum, Kanban', 'linear-gradient(135deg, #f39c12, #333)'),
('Continuous Delivery', 'Jez Humble', 'Reliable Software Releases.', 'Shelf 2B', 'DevOps, CI/CD, Infrastructure', 'linear-gradient(135deg, #444, #1abc9c)'),
('Site Reliability Engineering', 'Betsy Beyer', 'Google SRE book.', 'Shelf 2B', 'SRE, DevOps, Reliability', 'linear-gradient(135deg, #1e3c72, #333)'),
('Accelerate', 'Nicole Forsgren', 'Building High Performing Teams.', 'Shelf 4D', 'DevOps, Metrics, Culture', 'linear-gradient(135deg, #e67e22, #333)'),
('The Phoenix Project', 'Gene Kim', 'DevOps business novel.', 'Shelf 4D', 'DevOps, IT, Management', 'linear-gradient(135deg, #c0392b, #333)'),
('Building Microservices', 'Sam Newman', 'Distributed systems.', 'Shelf 2B', 'Microservices, Architecture, Cloud', 'linear-gradient(135deg, #3498db, #333)'),
('Release It!', 'Michael T. Nygard', 'Design for Production.', 'Shelf 2B', 'Architecture, Reliability, Systems', 'linear-gradient(135deg, #444, #e74c3c)'),
('Fundamentals of Software Architecture', 'Mark Richards', 'Comprehensive Arch guide.', 'Shelf 2B', 'Architecture, Patterns, Soft Skills', 'linear-gradient(135deg, #2c3e50, #2980b9)'),
('Microservices Patterns', 'Chris Richardson', 'Enterprise patterns.', 'Shelf 2B', 'Microservices, Patterns, Architecture', 'linear-gradient(135deg, #1abc9c, #2980b9)'),
('Designing Data-Intensive Applications', 'Martin Kleppmann', 'The big data book.', 'Shelf 3C', 'Data Systems, Scalability, Architecture', 'linear-gradient(135deg, #444, #8e44ad)'),
('Kubernetes up & Running', 'Kelsey Hightower', 'Cloud native basics.', 'Shelf 2B', 'Kubernetes, Cloud, Docker', 'linear-gradient(135deg, #3498db, #444)'),
('Docker Deep Dive', 'Nigel Poulton', 'Containerization guide.', 'Shelf 2B', 'Docker, Containers, DevOps', 'linear-gradient(135deg, #1e3c72, #444)'),
('Pro Git', 'Scott Chacon', 'Mastering Git.', 'Shelf 1A', 'Git, Version Control, Tools', 'linear-gradient(135deg, #f34f29, #333)'),
('Programming Pearls', 'Jon Bentley', 'Algorithm gems.', 'Shelf 3C', 'Algorithms, Programming, Math', 'linear-gradient(135deg, #27ae60, #333)'),
('Python Crash Course', 'Eric Matthes', 'Fast track Python.', 'Shelf 1A', 'Python, Programming, Projects', 'linear-gradient(135deg, #2980b9, #f1c40f)'),
('Learn Python the Hard Way', 'Zed Shaw', 'Foundations of Python.', 'Shelf 1A', 'Python, Programming, Basics', 'linear-gradient(135deg, #c0392b, #333)'),
('Effective C++', 'Scott Meyers', 'Improving C++ programs.', 'Shelf 1A', 'C++, Programming, Performance', 'linear-gradient(135deg, #34495e, #333)'),
('The C Programming Language', 'Brian Kernighan', 'The K&R book.', 'Shelf 1A', 'C, Programming, Foundations', 'linear-gradient(135deg, #444, #111)'),
('Think Python', 'Allen B. Downey', 'How to think like a CSR.', 'Shelf 1A', 'Python, Logic, Programming', 'linear-gradient(135deg, #27ae60, #333)'),
('JavaScript: The Good Parts', 'Douglas Crockford', 'Core JS features.', 'Shelf 1A', 'JavaScript, Web, Programming', 'linear-gradient(135deg, #f1c40f, #333)'),
('You Don\'t Know JS', 'Kyle Simpson', 'Deep JS dives.', 'Shelf 1A', 'JavaScript, Scopes, Closures', 'linear-gradient(135deg, #444, #f1c40f)');
